/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package L4G;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hpmdu
 */
public class QLLop extends javax.swing.JFrame {

    /**
     * Creates new form QLLop
     */
    
    // Default var for maLop
    private String maLop = "CNTT-D17";
    
    public QLLop() {
        initComponents();
//        this.showList();
    }
    
    public void setMaLop(String maLop){
        this.maLop = maLop;
    }
    
    public void showList(){
        DefaultTableModel dtm = (DefaultTableModel) classTable.getModel();
        Connection conn = new MssqlConnection().getConnection();
        try{
            String sql = "SELECT * FROM SINHVIEN WHERE MALOP = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, this.maLop);
            ResultSet rs = ps.executeQuery();
            Vector vt;
            while(rs.next()){
                vt = new Vector();
                vt.add(rs.getString("MASV"));
                vt.add(rs.getString("HOTEN"));
                vt.add(rs.getDate("NGAYSINH"));
                vt.add(rs.getString("DIACHI"));
                vt.add(rs.getString("MALOP"));
                vt.add(rs.getString("TENDN"));
                vt.add(rs.getString("MATKHAU"));
                dtm.addRow(vt);
            }
            classTable.setModel(dtm);
            ps.close();
            rs.close();
            conn.close();
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    public void updateTable(SinhVien sv){
//        classTable.setValueAt(rs.getString("MASV"), classTable.getSelectedRow(), 0);
        classTable.setValueAt(sv.getHoTen(), classTable.getSelectedRow(), 1);
        classTable.setValueAt(sv.getNgaysinh(), classTable.getSelectedRow(), 2);
        classTable.setValueAt(sv.getDiaChi(), classTable.getSelectedRow(), 3);
//        classTable.setValueAt(rs.getString("MALOP"), classTable.getSelectedRow(), 4);
        classTable.setValueAt(sv.getTenDN(), classTable.getSelectedRow(), 5);
        if (sv.getMatKhau() != null) classTable.setValueAt(sv.getMatKhau(), classTable.getSelectedRow(), 6);
    }
    
    public void insertTable(SinhVien sv){
        DefaultTableModel dtm = (DefaultTableModel) classTable.getModel();
        Vector vt = new Vector();
        vt.add(sv.getMaSv());
        vt.add(sv.getHoTen());
        vt.add(sv.getNgaysinh());
        vt.add(sv.getDiaChi());
        vt.add(sv.getMaLop());
        vt.add(sv.getTenDN());
        vt.add(sv.getMatKhau());
        dtm.addRow(vt);
        System.out.println("Nhập vào table MASV: " + sv.getMaSv());
        classTable.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        classTable = new javax.swing.JTable();
        editBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        insertBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Quản lý lớp học");

        classTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MASV", "Họ tên", "Ngày sinh", "Địa chỉ", "Mã lớp", "Tên DN", "Mật khẩu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(classTable);
        if (classTable.getColumnModel().getColumnCount() > 0) {
            classTable.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        editBtn.setText("Sửa");
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });

        backBtn.setText("Quay lại");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        insertBtn.setText("Thêm");
        insertBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertBtnMouseClicked(evt);
            }
        });

        delBtn.setText("Xóa");
        delBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(insertBtn)
                                .addGap(18, 18, 18)
                                .addComponent(delBtn)
                                .addGap(18, 18, 18)
                                .addComponent(editBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editBtn)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(insertBtn)
                        .addComponent(delBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        // TODO add your handling code here:
        String maSV = classTable.getValueAt(classTable.getSelectedRow(), 0).toString();
        System.out.println("MASV chọn: " + maSV);
        InsertAndUpdateSV updateSV = new InsertAndUpdateSV();
        updateSV.setEditSV(true);
        updateSV.setMaSV(maSV);
        updateSV.setMalop(maLop);
        updateSV.getInforSV();
        updateSV.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosed(WindowEvent e) {
                // call terminate
                try{
                    Connection conn = new MssqlConnection().getConnection();
                    String sql = "EXEC SP_SEL_ENCRYPT_SINHVIEN ?";
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setString(1, maSV);
                    ResultSet rs = ps.executeQuery();
                    if (rs.next()){
//                            SinhVien sv = new SinhVien(rs.getString("MASV"), rs.getString("HOTEN"), rs.getDate("NGAYSINH"), 
//                                rs.getString("DIACHI"), rs.getString("MALOP"), rs.getString("TENDN"), rs.getString("MATKHAU"));
                        updateTable(updateSV.getSv());
                    }
                }
                catch(SQLException excp){
                    excp.printStackTrace();
                }
            }
        });
        updateSV.setVisible(true);
    }//GEN-LAST:event_editBtnMouseClicked

    private void insertBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtnMouseClicked
        // TODO add your handling code here:
        InsertAndUpdateSV svf = new InsertAndUpdateSV();
        svf.setEditSV(false);
        if (classTable.getRowCount() != 0){
            String maSvLast = classTable.getValueAt(classTable.getRowCount() - 1, 0).toString();
            int maSo = Integer.parseInt(maSvLast.substring(2, maSvLast.length()));
            String t = maSo < 9 ? "SV0" + (maSo + 1):"SV" + (maSo + 1);
            System.out.println("MASV mới: " + t );
            svf.setMaSV(t);
            svf.addWindowListener(new WindowAdapter(){
                @Override
                public void windowClosed(WindowEvent e) {
                    // call terminate
                    try{
                        Connection conn = new MssqlConnection().getConnection();
                        String sql = "EXEC SP_SEL_ENCRYPT_SINHVIEN ?";
                        PreparedStatement ps = conn.prepareStatement(sql);
                        ps.setString(1, t);
                        ResultSet rs = ps.executeQuery();
                        if (rs.next()){
                            SinhVien sv = new SinhVien(rs.getString("MASV"), rs.getString("HOTEN"), rs.getDate("NGAYSINH"), 
                                rs.getString("DIACHI"), rs.getString("MALOP"), rs.getString("TENDN"), rs.getString("MATKHAU"));
                            insertTable(svf.getSv());
                        }
                    }
                    catch(SQLException excp){
                        excp.printStackTrace();
                    }
                }
            });
        }
        else{
            svf.setMaSV("SV01");
        }
        svf.setMalop(this.maLop);
        svf.setVisible(true);
    }//GEN-LAST:event_insertBtnMouseClicked

    private void delBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delBtnMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) classTable.getModel();
        Connection conn = new MssqlConnection().getConnection();
        try{
            String sql = "DELETE FROM SINHVIEN WHERE MASV = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, classTable.getValueAt(classTable.getSelectedRow(), 0).toString());
            int selectedOption = JOptionPane.showConfirmDialog(null,
                    "Dữ liệu sẽ xóa trực tiếp vào cơ sở dữ liệu. Bạn có muốn tiếp tục",
                    "Choose",
                    JOptionPane.YES_NO_OPTION);
                if (selectedOption == JOptionPane.YES_OPTION) {
                    ps.execute();
                    dtm.removeRow(classTable.getSelectedRow());
                    classTable.setModel(dtm);
                }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_delBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLLop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable classTable;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
