/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package L4G;

import java.awt.event.WindowEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hpmdu
 */
public class QLNV extends javax.swing.JFrame {

    /**
     * Creates new form QLNV
     */
    
    private Connection conn = new MssqlConnection().getConnection();
//    private List<NhanVien> listNV = new ArrayList<NhanVien>();
    public QLNV() {
        initComponents();
        saveBtn.setEnabled(false);
        this.load();
    }
    
    public void load(){
        DefaultTableModel dtm = (DefaultTableModel) nvList.getModel();
        RSA rsa = new RSA();
        try{
            String sql = "EXEC SP_SEL_ALL_PUBLIC_ENCRYPT_NHANVIEN";
            PreparedStatement ps = this.conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Vector vt = new Vector();
                vt.add(rs.getString("MANV"));
                vt.add(rs.getString("HOTEN"));
                vt.add(rs.getString("EMAIL"));
                vt.add(rsa.decrypt(rs.getString("LUONG"), rsa.getPrivateKey(rsa.getFileInBytes(new File("privateKey.txt")))));
                dtm.addRow(vt);
            }
            nvList.setModel(dtm);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public void refresh(NhanVien nv){
//        RSA rsa = new RSA();
        DefaultTableModel dtm = (DefaultTableModel) nvList.getModel();
        Vector vt = new Vector();
        vt.add(nv.getMaNV());
        vt.add(nv.getHoTen());
        vt.add(nv.geteMail());
        vt.add(nv.getLuong());
        dtm.addRow(vt);
        nvList.setModel(dtm);
    }
    
    public void updateRow(NhanVien nv){
//        DefaultTableModel dtm = (DefaultTableModel) nvList.getModel();
        nvList.setValueAt(nv.getMaNV(), nvList.getSelectedRow(), 0);
        nvList.setValueAt(nv.getHoTen(), nvList.getSelectedRow(), 1);
        nvList.setValueAt(nv.geteMail(), nvList.getSelectedRow(), 2);
        nvList.setValueAt(nv.getLuong(), nvList.getSelectedRow(), 3);
    }
    
    public void setEnableSaveBtn(boolean visible){
        saveBtn.setEnabled(visible);
        insertBtn.setEnabled(!visible);
        delBtn.setEnabled(!visible);
        editBtn.setEnabled(!visible);
        maNV.setEditable(!visible);
    }
    
    public void eraseTextField(){
        maNV.setText("");
        hoTen.setText("");
        eMail.setText("");
        luong.setText("");
        tenDN.setText("");
        matKhau.setText("");
    }
    
    public boolean maNVExist(String maNV){
        try{
            String sql = "SELECT MANV FROM NHANVIEN WHERE MANV = ?";
            PreparedStatement ps = this.conn.prepareStatement(sql);
            ps.setString(1, maNV);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) return true;
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        return false;
    }
    
    public boolean isNum(String num){
        try{
            Integer.parseInt(num);
            return true;
        }
        catch(NumberFormatException e){
            e.printStackTrace();
        }
        return false;
    }
    
    public void saveToDB(NhanVien nv){
        Hash hash = new Hash();
        RSA rsa = new RSA();
        String sql = "EXEC SP_INS_PUBLIC_ENCRYPT_NHANVIEN ?, ?, ?, ?, ?, ?, ?";
        System.out.println(nv);
        try{
            PreparedStatement ps = this.conn.prepareStatement(sql);
            ps.setString(1, nv.getMaNV());
            ps.setString(2, nv.getHoTen());
            ps.setString(3, nv.geteMail());
            ps.setString(4, rsa.encrypt(nv.getLuong(), rsa.getPublicKey(rsa.getFileInBytes(new File("publicKey.txt")))));
            ps.setString(5, nv.getTenDN());
            ps.setString(6, hash.getSHA1(nv.getMatKhau()));
            ps.setString(7, "publicKey.txt");
            ps.execute();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        maNV = new javax.swing.JTextField();
        eMail = new javax.swing.JTextField();
        tenDN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hoTen = new javax.swing.JTextField();
        luong = new javax.swing.JTextField();
        matKhau = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        nvList = new javax.swing.JTable();
        insertBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Danh mục nhân viên");

        jLabel2.setText("Thông tin nhân viên");

        jLabel3.setText("Mã NV");

        jLabel4.setText("Email");

        jLabel5.setText("Tên đăng nhập");

        jLabel6.setText("Họ tên");

        jLabel7.setText("Lương");

        jLabel8.setText("Mật khẩu");

        nvList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ NHÂN VIÊN", "HỌ TÊN", "EMAIL", "LUONG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(nvList);

        insertBtn.setText("Thêm");
        insertBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertBtnMouseClicked(evt);
            }
        });

        delBtn.setText("Xóa");
        delBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delBtnMouseClicked(evt);
            }
        });

        editBtn.setText("Sửa");
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });

        saveBtn.setText("Lưu");
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
        });

        exitBtn.setText("Thoát");
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(insertBtn)
                        .addGap(18, 18, 18)
                        .addComponent(delBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editBtn)
                        .addGap(18, 18, 18)
                        .addComponent(saveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(90, 90, 90)
                                        .addComponent(eMail, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(luong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                    .addComponent(matKhau, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hoTen, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(83, 83, 83)
                                .addComponent(maNV, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(eMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tenDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertBtn)
                    .addComponent(delBtn)
                    .addComponent(editBtn)
                    .addComponent(saveBtn)
                    .addComponent(exitBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
        // TODO add your handling code here:
        if (saveBtn.isEnabled()){
            maNV.setEditable(true);
            try{
                String sql = "";
                boolean changePw = false;
                boolean ok = true;
                if (hoTen.getText().trim().isEmpty() || eMail.getText().trim().isEmpty() || 
                        tenDN.getText().trim().isEmpty() || luong.getText().trim().isEmpty()){
                    ok = false;
                }
                else if (!isNum(luong.getText().trim())){
                    ok = false;
                }
                if (!matKhau.getText().trim().equals("")) {
                    changePw = true;
                    sql = "SP_UPDATE_ENCRYPT_NHANVIEN_WITH_MATKHAU ?, ?, ?, ?, ?, ?";
                }
                else{
                    sql = "SP_UPDATE_ENCRYPT_NHANVIEN_WITHOUT_MATKHAU ?, ?, ?, ?, ?";
                }
                if (ok){
                    NhanVien nv = new NhanVien(maNV.getText().trim(), hoTen.getText().trim(), eMail.getText().trim(),
                        luong.getText().trim(),tenDN.getText().trim(),matKhau.getText().trim());
                    RSA rsa = new RSA();
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setString(1, nv.getMaNV());
                    ps.setString(2, nv.getHoTen());
                    ps.setString(3, nv.geteMail());
                    ps.setString(4, rsa.encrypt(nv.getLuong(), rsa.getPublicKey(rsa.getFileInBytes(new File("publicKey.txt")))));
                    ps.setString(5, nv.getTenDN());
                    if (changePw){
                        Hash hash = new Hash();
                        System.out.println("doi mk");
                        ps.setString(5, hash.getSHA1(nv.getMatKhau()));
                    }
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Thay doi thanh cong");
                    this.setEnableSaveBtn(false);
                    this.eraseTextField();
                    this.updateRow(nv);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Vui long dien day du thong tin", "Canh bao", JOptionPane.WARNING_MESSAGE);
                }

            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_saveBtnMouseClicked

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        // TODO add your handling code here:
        if (editBtn.isEnabled()){
            RSA rsa = new RSA();
            try{
                String sql = "EXEC SP_SEL_TO_UPDATE '" + nvList.getValueAt(nvList.getSelectedRow(), 0).toString() + "'";
                PreparedStatement ps = this.conn.prepareStatement(sql);
                ResultSet rs = ps.executeQuery();
                if (rs.next()){
                    maNV.setText(rs.getString("MANV"));
                    hoTen.setText(rs.getString("HOTEN"));
                    eMail.setText(rs.getString("EMAIL"));
                    luong.setText(rsa.decrypt(rs.getString("LUONG"), rsa.getPrivateKey(rsa.getFileInBytes(new File("privateKey.txt")))));
                    tenDN.setText(rs.getString("TENDN"));
                    this.setEnableSaveBtn(true);
                }
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_editBtnMouseClicked

    private void delBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delBtnMouseClicked
        // TODO add your handling code here:
        if (delBtn.isEnabled()){
            DefaultTableModel dtm = (DefaultTableModel) nvList.getModel();
            try{
                String sql = "DELETE FROM NHANVIEN WHERE MANV = ?";
                PreparedStatement ps = this.conn.prepareStatement(sql);
                ps.setString(1, nvList.getValueAt(nvList.getSelectedRow(), 0).toString());
                int selectedOption = JOptionPane.showConfirmDialog(null,
                    "Dữ liệu sẽ xóa trực tiếp vào cơ sở dữ liệu. Bạn có muốn tiếp tục",
                    "Choose",
                    JOptionPane.YES_NO_OPTION);
                if (selectedOption == JOptionPane.YES_OPTION) {
                    ps.execute();
                    dtm.removeRow(nvList.getSelectedRow());
                    nvList.setModel(dtm);
                }
            }
            catch(SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_delBtnMouseClicked

    private void insertBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBtnMouseClicked
        // TODO add your handling code here:
        if (insertBtn.isEnabled()){
            if (maNV.getText().trim().equals("") && hoTen.getText().trim().equals("") && eMail.getText().trim().equals("")
                && luong.getText().trim().equals("") && tenDN.getText().trim().equals("")
                && matKhau.getText().trim().equals("")){
                JOptionPane.showMessageDialog(this, "Vui long khong de trong", "Canh bao", JOptionPane.WARNING_MESSAGE);
            }
            else if (this.maNVExist(maNV.getText().trim())){
                JOptionPane.showMessageDialog(this, "Ma nhan vien da ton tai", "Canh bao", JOptionPane.WARNING_MESSAGE);
            }
            else if (!this.isNum(luong.getText().trim())){
                JOptionPane.showMessageDialog(this, "Nhap luong nhan vien sai", "Canh bao", JOptionPane.WARNING_MESSAGE);
            }
            else{
                NhanVien nv = new NhanVien(maNV.getText(), hoTen.getText(), eMail.getText(),
                    luong.getText(),tenDN.getText(),matKhau.getText());
                this.saveToDB(nv);
                JOptionPane.showMessageDialog(this, "Them nhan vien thanh cong");
                this.refresh(nv);
                this.eraseTextField();
            }
        }
    }//GEN-LAST:event_insertBtnMouseClicked

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delBtn;
    private javax.swing.JTextField eMail;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField hoTen;
    private javax.swing.JButton insertBtn;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField luong;
    private javax.swing.JTextField maNV;
    private javax.swing.JPasswordField matKhau;
    private javax.swing.JTable nvList;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField tenDN;
    // End of variables declaration//GEN-END:variables
}
