/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author hpmdu
 */
public class HideFrame extends javax.swing.JFrame {

    /**
     * Creates new form HideFrame
     */
    
    private String keyString;
    private String messages;
    private boolean exec;
    private int imageHeight;
    private int imageWidth;
    
    public HideFrame() {
        initComponents();
        this.setResizable(false);
        messageField.setLineWrap(true);
        keyField.setText("");
        warning.setText("");
        this.exec = false;
    }

    public String getKeyString() {
        return keyString;
    }

    public String getMessages() {
        return messages;
    }

    public boolean isExec() {
        return exec;
    }

    public void setImageHeight(int imageHeight) {
        this.imageHeight = imageHeight;
    }

    public void setImageWidth(int imageWidth) {
        this.imageWidth = imageWidth;
    }
    
    public int getTotalCharHidden(){
        int blockHeight = keyField.getText().trim().length();
        int blockWidth = 8;
        return ((imageHeight * imageWidth) / (blockHeight * blockWidth * 8)) * 3;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageField = new javax.swing.JTextArea();
        executeBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        keyField = new javax.swing.JPasswordField();
        closeBtn = new javax.swing.JButton();
        warning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel1.setText("Messages");

        messageField.setColumns(20);
        messageField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        messageField.setRows(5);
        jScrollPane1.setViewportView(messageField);

        executeBtn.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        executeBtn.setText("Execute");
        executeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel2.setText("Key");

        keyField.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        keyField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                keyFieldFocusLost(evt);
            }
        });

        closeBtn.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        warning.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        warning.setForeground(new java.awt.Color(255, 0, 0));
        warning.setText("onKeyFieldFocus to show how many characters can be hiden ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(executeBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(keyField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(warning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(warning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executeBtn)
                    .addComponent(closeBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeBtnActionPerformed
        // TODO add your handling code here:
        String keyString = keyField.getText().trim();
        String messages = messageField.getText().trim();
        if (keyString.isEmpty()){
            JOptionPane.showMessageDialog(this, "Key is null", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if (keyString.length() > imageHeight){
            JOptionPane.showMessageDialog(this, "Key's length is too long", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if (messages.isEmpty()){
            JOptionPane.showMessageDialog(this, "Message is null", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if (messages.length() > getTotalCharHidden()){
            JOptionPane.showMessageDialog(this, 
                    String.format("Message's length: %d is too long", messages.length())
                    , "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            this.keyString = keyString;
            this.messages = messages;
            this.exec = true;
            this.dispose();
        }
    }//GEN-LAST:event_executeBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void keyFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_keyFieldFocusLost
        // TODO add your handling code here:
        int blockHeight = keyField.getText().trim().length();
        int blockWidth = 8;
        if (blockHeight > imageHeight) warning.setText("Key's length is too long");
        else if (blockHeight == 0) warning.setText("Key is null");
        else{
            // Tính số lượng kí tự có thể giấu được
            int totalCharHidden = getTotalCharHidden();
            warning.setText(String.format("Key's length: %d"
                    + " | Characters can be hidden in 3 channel: %d", blockHeight, totalCharHidden));
        }
    }//GEN-LAST:event_keyFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HideFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HideFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HideFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HideFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HideFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton executeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField keyField;
    private javax.swing.JTextArea messageField;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
