/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javafx.scene.layout.Border;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import wulee.WuLeeLastedVersion;

/**
 *
 * @author hpmdu
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    static{
        // Load thư viện vào
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
    }
    
    private String path = "";
    private final WuLeeLastedVersion wulee = new WuLeeLastedVersion();
    
    public MainFrame() {
        initComponents();
        this.setResizable(false);
        setup();
    }
    
    public void setup(){
        this.process.setEditable(false);
        this.process.setLineWrap(true);
        displayProcessLine("Program is ready.....");
    }
    
    public void displayProcessLine(String line){
        Date d = new Date();
        
        this.process.append(String.format("[%d:%s:%s] %s\n", d.getHours(), 
                d.getMinutes() < 10 ? "0"+d.getMinutes():d.getMinutes(), 
                d.getSeconds() < 10 ? "0"+d.getSeconds():d.getSeconds(), 
                line));
    }
    
    public void calculate(){
        
    }
    
    public MainFrame getMainFrameComponent(){
        return this;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        browseBtn = new javax.swing.JButton();
        retrieveBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        hideBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        process = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Wu - Lee Steganography");

        browseBtn.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        browseBtn.setText("Browse");
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });

        retrieveBtn.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        retrieveBtn.setText("Retrieve");
        retrieveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieveBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        hideBtn.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        hideBtn.setText("Hide");
        hideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideBtnActionPerformed(evt);
            }
        });

        process.setColumns(20);
        process.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        process.setRows(5);
        jScrollPane2.setViewportView(process);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(browseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(retrieveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(browseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retrieveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "JPG & GIF Images", "jpg", "png", "jpeg", "gif");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            this.path = chooser.getSelectedFile().getAbsolutePath();
            wulee.setCoverImage(this.path);
            if (wulee.coverIsNull()){
                displayProcessLine("Something wrong with Opencv module. Please check again.");
            }
            else displayProcessLine(String.format("Import image at %s successfully!\nThe longer key string get, the less characters hidden", 
                    this.path));
        }
    }//GEN-LAST:event_browseBtnActionPerformed

    private void hideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideBtnActionPerformed
        // TODO add your handling code here:
        if (wulee.coverIsNull()){
            JOptionPane.showMessageDialog(this, "Image is null", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            HideFrame hideFrame = new HideFrame();
            hideFrame.setVisible(true);
            this.setEnabled(false);
            hideFrame.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e){
                    if (hideFrame.isExec()){
                        wulee.setKey(hideFrame.getKeyString());
                        wulee.setMessage(hideFrame.getMessages());
                    }
                    // Tại sao phải ghi MainFrame.this.... ? Vì bên trong function override này thì this sẽ không phải là của MainFrame
                    // mà là của WindowAdapter
                    MainFrame.this.setEnabled(true);
                    MainFrame.this.setAlwaysOnTop(true);
                    MainFrame.this.setAlwaysOnTop(false);
                    displayProcessLine("Begin to hide...");
                    wulee.hide();
                    wulee.setKeyToNull();
                    wulee.resetWhenHide();
                    displayProcessLine("Hiding messages is success, please save your stego image.");
                }
            });
        }
    }//GEN-LAST:event_hideBtnActionPerformed

    private void retrieveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieveBtnActionPerformed
        // TODO add your handling code here:
        if (wulee.coverIsNull()){
            JOptionPane.showMessageDialog(this, "Image is null", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            // frame nhập key và retrieveMax
            InputKeyAndLength inpKL = new InputKeyAndLength();
            inpKL.setVisible(true);
            inpKL.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e){
                    if (inpKL.isEveryThingSet()){
                        // Nhập khóa
                        wulee.setKey(inpKL.getKeyString());
                        // Nhập độ dài chuỗi msg
                        wulee.setRetrieveMax(inpKL.getLength());
                        // Bắt đầu trích xuất
                        wulee.retrieve();
                        RetrieveFrame retrieveFrame = new RetrieveFrame();
                        retrieveFrame.setRetrieveMsg(wulee.getRetrieveMessage());
                        retrieveFrame.setVisible(true);
                        wulee.resetWhenRetrieve();
                    }
                }
            });
            
        }
    }//GEN-LAST:event_retrieveBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if (wulee.coverIsNull()){
            JOptionPane.showMessageDialog(this, "Image is null", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            JFileChooser saver = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG & GIF Images", "jpg", "png", "jpeg", "gif");
            saver.setFileFilter(filter);
            int returnVal = saver.showSaveDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION){
                String fileName = saver.getSelectedFile().getAbsolutePath();
                if (!fileName.matches("(.*).png")) fileName += ".png";
                wulee.saveStegoImage(fileName);
                displayProcessLine(String.format("Save image successfully to %s", fileName));
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseBtn;
    private javax.swing.JButton hideBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea process;
    private javax.swing.JButton retrieveBtn;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
