/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author hpmdu
 */
public class PreviewImage extends javax.swing.JFrame {

    /**
     * Creates new form PreviewImage
     */
    public PreviewImage() {
        initComponents();
        this.setResizable(false);
//        this.setSize(1920, 1080);
    }
    
    public void imageShow(String path){
        try{
            BufferedImage buffImg = ImageIO.read(new File(path));
//            imageSize.setText(String.format("%d x %d", buffImg.getWidth(), buffImg.getHeight()));
            double height = buffImg.getHeight();
            double width = buffImg.getWidth();
            if (width > height){
                double scaleWidth = 1920/3;
                if (width > scaleWidth){
                    height *= (scaleWidth / width);
                    width = scaleWidth;
                }
            }
            else{
                double scaleHeight = 1080/3;
                if (height > scaleHeight){
                    width *= (scaleHeight / height);
                    height = scaleHeight;
                }
            }
            
            imagePlace.setText("");
            this.setSize((int)width + 16, (int)height + 38);
            imagePlace.setSize((int)width, (int)height);
//            imagePlace.setIcon(new ImageIcon(buffImg.getScaledInstance((int)width, (int)height, Image.SCALE_DEFAULT)));
            imagePlace.setIcon(new ImageIcon(buffImg.getScaledInstance(imagePlace.getWidth(), imagePlace.getHeight(), Image.SCALE_DEFAULT)));
        }
        catch(IOException e){
            imagePlace.setText("There is something wrong");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePlace = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        imagePlace.setText("Show image here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePlace, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePlace, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreviewImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreviewImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreviewImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreviewImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreviewImage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagePlace;
    // End of variables declaration//GEN-END:variables
}
